### ISSUE TITLE
Number of occurrences of the letter "o" is inconclusive and bizarre.

### ISSUE THREAD

**Issue by brudski** [verfehlix/predictooor#1]
Please fix immediately, this is embarrassing and unprofessional

**Comment by verfehlix** [comment]
https://github.com/verfehlix/predictooor/commit/96886611edd784858a4d76205942f481c9412da2

**Comment by verfehlix** [comment]
@brudski as i have now gone out of my way to answer your desires, It is imperative that you star this repository immediately, OR ELSE
